### ISSUE TITLE
2.6 for arm64 problem in apply push option

### ISSUE THREAD

**Issue by mahdiyousef** [OpenVPN/openvpn#227]
I can successful installed new version 2.6 release version today without any error.
Any config connecting show me error in connection process and loop retrying connection.
Please resolve this problem.
![image](https://user-images.githubusercontent.com/76701040/215019752-2c802e33-a103-4b07-a2c4-38b9fb80bb5f.png)

**Comment by flichtenheld** [comment]
Moved to openvpn since not related to GUI

**Comment by schwabe** [comment]
Yes this happens if the server does not push a cipher that is in the data-ciphers and also the cipher the server indicates via OCC is also not in the data-ciphers list. You need to either use `compat-mode` to get deprecated behaviour to connect to an older peer or get your server provider to send you a fixed profile.

**Comment by schwabe** [comment]
This works as expected and is described here in detail: https://github.com/OpenVPN/openvpn/blob/master/doc/man-sections/cipher-negotiation.rst

**Comment by mahdiyousef** [comment]
> This works as expected and is described here in detail: https://github.com/OpenVPN/openvpn/blob/master/doc/man-sections/cipher-negotiation.rst

How to use this and how to resolve problem?
