### ISSUE TITLE
ccd files are no longer read (permission denied) after upgrade to 2.6.0 (openvpn-server)

### ISSUE THREAD

**Issue by Claus-Schumacher** [OpenVPN/openvpn#230]
**Describe the bug**
Without changing any config file, neither on client nor server side, the server complains, ccd files are no longer readable.

`Could not access file 'fmly/ccd/name': Permission denied (errno=13)`

**To Reproduce**
It always reproduces.

**Expected behavior**
Behave like 2.5.8 is that regard.

**Version information (please complete the following information):**
 - OS: Arch Linux
 - OpenVPN version: 2.6.0
 - Kernel: 5.15.0-1-lts

**Additional context**
Of course that ccd folder is in the server.conf:
`client-config-dir fmly/ccd`

The ccd file itself and all its subfolders have ownership `openvpn:network` and are readable and executable, respectively.

Downgrading to 2.5.8 immediately fixes the issue.

I'm happy to give as many more information as you need!

**Comment by TinCanTech** [comment]
@Claus-Schumacher It is generally considered to be _more secure_ to create a dedicated user and group for the Openvpn daemon. eg: `openvpn:openvpn`

**Comment by cron2** [comment]
hi,

On Mon, Jan 30, 2023 at 09:23:22AM -0800, DefaultUser0815 wrote:
> Oh dear,
> 
> I was afraid it was that easy. Crazy enough that it was working with `user nobody` and `group nobody` until now. 

Our user/group handling changed on Linux, so it's well possible that
we kept *extra* groups in 2.5, enabling access to the ccd/ files, and
now we really do a more thorough job, going to nobody/nobody "and nothing
else"...

So, sorry for breaking your setup, this wasn't intentional :-)

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
