### ISSUE TITLE
Options error: Unrecognized option --keysize

### ISSUE THREAD

**Issue by mxinran** [OpenVPN/openvpn#231]

**Comment by mxinran** [comment]
help,when i import config ,click for connection ,then prompt:
Options error: Unrecognized option or missing or extra parameter(s) in my_expressvpn_usa_-_new_york_udp.ovpn:22: keysize (2.6.0)
Use --help for more information.

**Comment by flichtenheld** [comment]
https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#Option:--keysizeStatus:Pendingremoval says

The --keysize option was only useful to change the key length when using the BF, CAST6 or RC2 ciphers. For all other ciphers the key-size is fixed with the chosen cipher. As OpenVPN v2.6 will no longer support any of these variable length ciphers, this option will be removed as well to avoid confusion. 

You should try removing the option from your config. If it is actually requires the cipher might also need to be changed. But the error is definitely expected and correct.
