### ISSUE TITLE
Broken DCO data channel when "comp-lzo no" is pushed

### ISSUE THREAD

**Issue by lstipakov** [OpenVPN/openvpn#243]
When using Mullvad and dco driver, traffic doesn't flow. No errors in driver or openvpn log. 

Wireshark capture on udp port 1195 shows a lot of traffic to the mullvad server, but almost nothing in another direction except 83 bytes length packets, which are pings according to timestamps.

Looks like Mullval server doesn't like something about data packets generated by dco.

**Comment by cron2** [comment]
This was addressed with commit 4117d950788eebfaf6c9b5dde278e3a81b9e805d, part of 2.6.2 - when encountering this situation (client has all compression disallowed and DCO enabled, and the server pushes a compression setting nevertheless) 2.6.2+ will now abort with a clear error message, instead of creating an "everything looks good but not traffic passes" situation.

**Comment by cron2** [comment]
This was addressed with commit 4117d950788eebfaf6c9b5dde278e3a81b9e805d, part of 2.6.2 - when encountering this situation (client has all compression disallowed and DCO enabled, and the server pushes a compression setting nevertheless) 2.6.2+ will now abort with a clear error message, instead of creating an "everything looks good but not traffic passes" situation.
