### ISSUE TITLE
Cant Start OpenVPN Server

### ISSUE THREAD

**Issue by NoahConstrictr** [OpenVPN/openvpn#250]
**Describe the bug**
I cant start the OpenVPN server on my Raspberry Pi. It tells me to use the command "journalctl -xe" and when I do, it gives a lot of info that I don't understand.

Feb 12 11:02:56 raspberrypi ovpn-pivpn[17947]: Use --help for more information.
Feb 12 11:02:56 raspberrypi systemd[1]: [openvpn@pivpn.service](mailto:openvpn@pivpn.service): Main process exited>
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: [Debian -- User Support](https://www.debian.org/support)
░░
░░ An ExecStart= process belonging to unit [openvpn@pivpn.service](mailto:openvpn@pivpn.service) has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Feb 12 11:02:56 raspberrypi systemd[1]: [openvpn@pivpn.service](mailto:openvpn@pivpn.service): Failed with result >
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: [Debian -- User Support](https://www.debian.org/support)
░░
░░ The unit [openvpn@pivpn.service](mailto:openvpn@pivpn.service) has entered the 'failed' state with result 'exit>
Feb 12 11:02:56 raspberrypi systemd[1]: Failed to start OpenVPN connection to pivp>
░░ Subject: A start job for unit [openvpn@pivpn.service](mailto:openvpn@pivpn.service) has failed
░░ Defined-By: systemd
░░ Support: [Debian -- User Support](https://www.debian.org/support)
░░
░░ A start job for unit [openvpn@pivpn.service](mailto:openvpn@pivpn.service) has finished with a failure.
░░
░░ The job identifier is 24175 and the job result is failed.

**To Reproduce**
Steps to reproduce the behavior. Please make sure to not post any secrets like keys and passwords.
Make sure no residue of PiVPN or OpenVPN is in any files. (I've tried reinstalling many times) Download PiVPN and configure it to run OpenVPN. Try to start OpenVPN server.

**Expected behavior**
Access point opens up and clients can connect.

**Version information (please complete the following information):**
 - OS: Latest version of Raspberry Pi OS with recommended software
 - OpenVPN version: OpenVPN 2.6.0
 - Repeat for peer if relevant

**Additional context**
I've uploaded an issue to the official OpenVPN forums, but thr forums are small and no one is responding. Help appreciated

**Comment by cron2** [comment]
Hi,

On Mon, Feb 13, 2023 at 10:39:56AM -0800, Noah Glorioso wrote:
> Feb 12 11:02:56 raspberrypi ovpn-pivpn[17947]: Use --help for more information.

This is the interesting bit.  Something in your config is invalid.

All the stuff from "systemd" is not truly interesting, the "ovpn-pivpn"
lines are (and I guess that the actual error is 1-2 lines above that one).

Find the config file, run "openvpn $myconfig" from the command line,
to see what it does not like.  Most likely you have some old cruft
in there like "--keysize" which has been removed from 2.6 (because
it stopped serving a useful purpose years ago).

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by NoahConstrictr** [comment]
Hey, I did the command and did see --keysize. How do I remove it?

**Comment by ordex** [comment]
It's in your config file. You can just remove it from there.
However, I wonder why is it even there in the first place..old script that generated the config?

**Comment by NoahConstrictr** [comment]
Where is the file located? I don't see it. Does it matter that I installed OpenVPN through PiVPN?

**Comment by ordex** [comment]
Yes, it does. pivpn is probably what created and saved your config file.
I presume your file is located somewhere in /etc/openvpn/ (or its subfolders)

**Comment by NoahConstrictr** [comment]
I see server.conf, is it in there?  I don't see anything that looks like it in the file, and I don't see any other files that looks like it in the whole /etc/openvpn directory.

**Comment by ordex** [comment]
isn't there any pivpn.conf ? given the service name that was trying to be started, I'd expect a file with that name.
But I truly am not familiar with pivpn, therefore I can't say for sure where it stores files.

This said, now that we have clarified that this is not a bug in OpenVPN, it may be more beneficial to open a thread on the forum (https://forums.openvpn.net)

**Comment by NoahConstrictr** [comment]
There is no pivpn.conf and I can't find anything to do with --keysize so I might just reinstall OpenVPN itself and see where that takes me. I have opened a forum, but the site is really small and haven't gotten any replies.

**Comment by schwabe** [comment]
Try something like `sudo grep -r keysize /etc/` . That should give you the config file. If not, your setup is really non-standard.

**Comment by NoahConstrictr** [comment]
I uninstalled OpenVPN and PiVPN and followed this guide: https://www.ovpn.com/en/guides/raspberry-pi-raspbian
When I run "sudo openvpn --config /etc/openvpn/ovpn.conf --daemon" it says I don't have a configuration file.

**Comment by NoahConstrictr** [comment]
Well I can't get it to work when installing OpenVPN itself. I'm not sure what to do now.

**Comment by NoahConstrictr** [comment]
I reinstalled OpenVPN through PiVPN, and ran this command to start the server "sudo systemctl start openvpn-server@server.service" and got this:

"Job for openvpn-server@server.service failed because the control process exited with error code.
See "systemctl status openvpn-server@server.service" and "journalctl -xe" for details."

"systemctl status openvpn-server@server.service" gives me this:

● openvpn-server@server.service - OpenVPN service for server
     Loaded: loaded (/lib/systemd/system/openvpn-server@.service; enabled; vend>
     Active: activating (auto-restart) (Result: exit-code) since Mon 2023-02-13>
       Docs: man:openvpn(8)
             https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
             https://community.openvpn.net/openvpn/wiki/HOWTO
    Process: 1917 ExecStart=/usr/sbin/openvpn --status /run/openvpn-server/stat>
   Main PID: 1917 (code=exited, status=1/FAILURE)
        CPU: 28ms

and "journalctl -xe" gives me this:

Feb 13 19:41:11 raspberrypi openvpn[2577]: Use --help for more information.
Feb 13 19:41:11 raspberrypi systemd[1]: openvpn-server@server.service: Main pro>
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStart= process belonging to unit openvpn-server@server.service has ex>
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Feb 13 19:41:11 raspberrypi systemd[1]: openvpn-server@server.service: Failed w>
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit openvpn-server@server.service has entered the 'failed' state with r>
Feb 13 19:41:11 raspberrypi systemd[1]: Failed to start OpenVPN service for ser>
░░ Subject: A start job for unit openvpn-server@server.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit openvpn-server@server.service has finished with a failu>
░░ 
░░ The job identifier is 7384 and the job result is failed.

Are there any more logs I can get for more information?

**Comment by cron2** [comment]
Hi,

On Mon, Feb 13, 2023 at 05:34:07PM -0800, Noah Glorioso wrote:
> I uninstalled OpenVPN and PiVPN and followed this guide: https://www.ovpn.com/en/guides/raspberry-pi-raspbian

These instructions will give you a ".zip" file, which will put some 
files in /etc/openvpn ("mv config/* /etc/openvpn").  One of these is
the openvpn config file and contains the "keysize" command, which should
not be there.

> When I run "sudo openvpn --config /etc/openvpn/ovpn.conf --daemon" it says I don't have a configuration file.

That sounds like you removed all the pivpn config so it's gone now.

What I would suggest to do next is to use the chat service of ovpn.com 
(on the URL above there is a chat window on the right side) - they
provide a commercial service, they provide a config file that contains
now-invalid config settings, they need to update their configs and provide
configs that do work.

Also, I really wish that VPN providers would follow what happens in the
OpenVPN world, and some of them would not be surprised by the removal
of a config option that has been logging warnings about "this will be
removed soon!!!" since 3+ years now...  but that's more a sidetrack grumble.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by TinCanTech** [comment]
The correct place to report this is to https://github.com/pivpn
