### ISSUE TITLE
Patch Release Changes Discoverability/Documentation

### ISSUE THREAD

**Issue by ite-klass** [OpenVPN/openvpn#255]
I see there's an OpenVPN update available from version `2.6.009` to version `2.6.010`. Where can I see what changed?

* The release/2.6 branch has time-recent commits
* There's a tag only for 2.6.0, but not any patch versions
* [release/2.6/Changes.rst](https://github.com/OpenVPN/openvpn/blob/release/2.6/Changes.rst) seems to get updated after a tag, but not with patch version information
* The [downloads page](https://openvpn.net/community-downloads/) links to tagged [v2.6.0/Changes.rst](https://github.com/OpenVPN/openvpn/blob/v2.6.0/Changes.rst), which is not updated with subsequent patch releases

**Comment by lstipakov** [comment]
If you see version bump like I004 -> I005, this means that OpenVPN binary hasn't been updated (it is still built from the same tag), but we have updated some dependencies, like OpenSSL or DCO driver.

You can see the changelog between those updates [here](https://community.openvpn.net/openvpn/wiki/Downloads).

**Comment by cron2** [comment]
Hi,

On Mon, Feb 20, 2023 at 12:48:34AM -0800, Jan Klass wrote:
> I see there's an OpenVPN update available from version `2.6.009` to version `2.6.010`. Where can I see the changes?

These version numbers are not really very helpful in this case - OpenVPN
version is always 2.6.0, but the installer version changed, I004->I005
due to "other components in the bundle having received updates", most
notably the ovpn-dco-win driver.

> * The release/2.6 branch has time-recent commits
> * There's a tag only for 2.6.0, but not any patch versions

Right.  If you look at "openvpn --version", you'll see that it's still
2.6.0

This situation is a bit confusing indeed - we had to re-release the
windows installer a couple of times, due to "windows specific problems",
but there was no new *OpenVPN* release in the meantime (which would
be 2.6.1, then, with a v2.6.1 tag and a ChangeLog)

See Lev's reply for "how to find info what is new in the installer 
re-release".

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by flichtenheld** [comment]
I don't think there is anything to do here except to make sure to document this on the download pages, which I believe we do. So closing this.

**Comment by ite-klass** [comment]
On https://openvpn.net/community-downloads/ there is no note of this though, right?

Only on the wiki download page?

**Comment by flichtenheld** [comment]
Generally for the last releases we have copied to text from Wiki to Website 1:1. So I assume we will do this for future occurrences of installer-only builds as well. Has been a while since we did an installer-only build, though.

Either way, having this issue open is not useful in reminding us to do it, IMHO.

In the long term I think the best improvement we could do for users is to give them update notifications in the application which can then also display differences to the installed version in a helpful and intelligent way. That has been on our wishlist for a long time, but so far no one has implemented it.
