### ISSUE TITLE
Configuration file not found

### ISSUE THREAD

**Issue by likeSnake** [OpenVPN/openvpn#277]
I downloaded the source code from GitHub and ran it directly on Android Studio, and it prompted me：

“CMake Error at CMakeLists.txt:31 (include):
include could not find load file:
openssl/openssl.cmake”
![image](https://user-images.githubusercontent.com/86227653/224882114-91748173-c0e2-4fa4-8514-4d5dc243c336.png)

I don't really know what this file does. I looked for configuration tutorials on the OpenVPN website, but due to my stupidity, I didn't find how to develop using OpenVPN source code in Android. I'm a college student and I want to learn more and write small projects in my spare time, and I would appreciate it if you knew what the problem was, or if you could tell me the address of the relevant tutorial

**Comment by cron2** [comment]
Hi,

On Mon, Mar 13, 2023 at 08:02:35PM -0700, likeSnake wrote:
> I'm a college student and I want to learn more and write small projects
> in my spare time, and I would appreciate it if you knew what the
> problem was, or if you could tell me the address of the relevant tutorial

OpenVPN is not a good project to start with, because it's not "small",
and fairly complex with the generic OpenVPN code parts and the android
specific additions.

I guess your error is because it's missing openssl source code, and
there should be a README file that explains what needs to be done.

We don't do full-featured tutorials, sorry.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by schwabe** [comment]
You should also not open the same bug twice. And you already opened this bug as https://github.com/schwabe/ics-openvpn/issues/1592
