### ISSUE TITLE
Openvpn 2.6.1 also problem in Windows 11 arm64

### ISSUE THREAD

**Issue by YousefMahdi** [OpenVPN/openvpn#291]
Hi 
Thanks for update to new version
My openvpn client 2.6.1 problem on windows 11 arm64 on parallels desktop on macos ventura
How to resolve this problem?
Log code:
[JP_vpn929481595.log](https://github.com/OpenVPN/openvpn/files/11016815/JP_vpn929481595.log)

**Comment by cron2** [comment]
The log says
```
2023-03-20 14:01:03 OPTIONS ERROR: failed to negotiate cipher with server.  Add the server's cipher ('AES-128-CBC') to --data-ciphers (currently 'AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305') if you want to connect to this server.
```
which means that your VPN provider is using an approach to cipher handling that has been outdated since 5+ years - so please open a ticket with them.

As a workaround, open your config file and add the line
```
data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305:AES-128-CBC
```
to it, to tell OpenVPN that this is an acceptable cipher.

I will proceed to close the ticket as this is not an OpenVPN bug (for which this is the right place) but a problem with the VPN Operator.
