### ISSUE TITLE
Does resolve-domains option works on Windows?

### ISSUE THREAD

**Issue by TitovLab** [OpenVPN/openvpn#305]
Please advise if the resolve-domains option should work on Windows 10 22H2 with OpenVPN 2.6.2? It use Name Resolution Policy Table (NRPT)?
Added to config:
```
dns search-domains my.local
dns server 1 address 192.168.125.2
dns server 1 resolve-domains my.local domain.com
```
But requests for domain.com are resolved through the ISP's DNS. Also command `Get-DnsClientNrptPolicy` show empty NRPT.
Perhaps I missed something?

**Comment by d12fk** [comment]
Currently it does not work, as the `--dns` just fills the values as if they were coming from the server via `--dhcp-option` at the moment. However, the (backend) implementation of the `--dns` option is almost finished and will go into code review in a few days, just need to tie some loose ends. Then, NRPT will be used so that you can do DNS routing / split DNS and the `resolve-domains` sub-option will start to work.

**Comment by TitovLab** [comment]
Thank you! Is it better to close this issue or should we wait for a new version to be released so that I can do some tests? Thanks again!

**Comment by d12fk** [comment]
Let's close it and in case you find issues open a new specific one then.
