### ISSUE TITLE
misleading message in TLS error: Unsupported protocol.

### ISSUE THREAD

**Issue by slesru** [OpenVPN/openvpn#332]
Hello!

I upgraded server to 2.6.3 from 2.5.9, and I see following messages in log;

TLS error: Unsupported protocol. This typically indicates that client and server have no common TLS version enabled. This can be caused by mismatched tls-version-min and tls-version-max options on client and server. If your OpenVPN client is between v2.3.6 and v2.3.2 try adding tls-version-min 1.0 to the client configuration to use TLS 1.0+ instead of TLS 1.0 only

Yes, I have old 2.3 clients.
And problem is solved by adding 
tls-version-min 1.0
to **server**  config

Message suggests to add this to client config. 
I think this is wrong.

Thank you!

**Comment by schwabe** [comment]
No. The message is not wrong. Adding `tls-version-min 1.0 to the client` to the client version will do exactly what it says. It will then talk also TLS 1.2 with your 2.6.3 server. What you are doing is allowing the server to speak TLS 1.0 with the old clients. Using TLS 1.0 is not recommended anymore.

**Comment by slesru** [comment]
TLS 1.0 and 1.1 are deprecated
    tls-version-min is set to 1.2 by default. OpenVPN 2.6.0 defaults to a minimum TLS version of 1.2 as TLS 1.0 and 1.1 should be generally avoided. Note that OpenVPN versions older than 2.3.7 use TLS 1.0 only.

from [Changes.rst](https://github.com/OpenVPN/openvpn/blob/master/Changes.rst)

So this message is  at least incomplete. 
And , just because we have versions older then 2.3.7,  my only choice to enable tls 1.0.

As user I'd like to have message which says that by default 2.6 minimal version is 1.2, not (only) what to do with very old 2.3 versions.

Thank you!

**Comment by schwabe** [comment]
The message gives you a way out for clients between 2.3.2 and 2.3.6 how to enable TLS 1.2 on them. It also indicates a mismatch between tls-min-version. The message is already quite I am not sure adding even more text is helpful. Also 2.3.2, which is the first version to support TLS 1.2 (with adding the `tls-version-min` to the config) has been releases 09-Apr-2014, so almost 10 years ago. I still believe it is better to suggest making the clients  TLS 1.2 compatible as our message suggests, rather than advising users to allow TLS 1.0 again.

**Comment by slesru** [comment]
Sorry, we can't through out all our 3g/4g routers right now.
2.3.18 is released in 2018, 5 years ago.
"Note that OpenVPN versions older than 2.3.7 use TLS 1.0 only."
Is this is right info?

**Comment by schwabe** [comment]
2.3.18 should do TLS 1.0+ in its default configuration. Maybe you are running some ancient OpenSSL version there as well but just retesting with here with a 2.3.x version needs have `--tls-version-max 1.1` added to make the connection fail against a 2.6.x server, otherwise it will happily do TLS 1.2.

**Comment by slesru** [comment]
Thank you!
It is possible, it is openwrt based routers with different versions.
