### ISSUE TITLE
A Javascript error ocurred in the main process: - ENOENT: No such file or directory when installing openvpn-connect-3.3.7.2979_signed on Windows 11

### ISSUE THREAD

**Issue by carolinapanther1** [OpenVPN/openvpn#345]
Operating System: Windows 11
OpenVPN Connect version: openvpn-connect-3.3.7.2979_signed
System info: LAPTOP-729N94OI | Operating System: Microsoft Windows 11 Home Single Language | OS Version: 10.0.22000 N/D Build 22000 | OS Manufacturer: Microsoft Corporation | System Configuration: Standalone Workstation | OS Build Type: Multiprocessor Free | System Manufacturer: LENOVO | System Model: 81LW | System Type: x64-based PC 

Bug Description:
When installing openvpn-connect-3.3.7.2979_signed that is on the onboarding launching OpenVPN Connect on Windows 11, after installation finishes an uncaught exception occurs with the error message "ENOENT: no such file or directory, open 'C\Users\{user}\ AppData\Roaming\OpenVPN Connect\loglovpn.log'".

Steps to Reproduce:

Launch installer  openvpn-connect-3.3.7.2979_signed on Windows 11.
After installation finishes it will trigger the following escenario
Trigger the scenario that causes the uncaught exception with the error message "ENOENT: no such file or directory, open 'C\Users\{user}\ AppData\Roaming\OpenVPN Connect\loglovpn.log'".

Attachments:
![image](https://github.com/OpenVPN/openvpn/assets/79677010/d399f670-be1d-4340-bfb9-56fae36a4cd4)

I don't know if the environment variable has to do something with this, I can't see the \loglovpn.log that is pointing the error
![image](https://github.com/OpenVPN/openvpn/assets/79677010/85140456-e439-43d9-9fb8-3d4d9f8a6a68)

**Comment by Pippin1st** [comment]
**IMPORTANT NOTE**
Bugs about OpenVPN Access Server, OpenVPN Connect or any other product by OpenVPN Inc. should be directly reported to OpenVPN Inc. at https://support.openvpn.net

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior. Please make sure to not post any secrets like keys and passwords.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Version information (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - OpenVPN version: [e.g. 2.5.8]
 - Repeat for peer if relevant

**Additional context**
Add any other context about the problem here.

**Comment by cron2** [comment]
Thanks for the good bug report.  Alas, the OpenVPN corp Connect team does not look into our issues, so these here are only for the open source implementations, not for Connect - so please report the bug via https://support.openvpn.net

**Comment by carolinapanther1** [comment]
If anyone encounters this issue this is how it was solved:

https://support.openvpn.com/hc/en-us/requests/464090?page=1

**Comment by ordex** [comment]
> If anyone encounters this issue this is how it was solved:
> 
> https://support.openvpn.com/hc/en-us/requests/464090?page=1

support tickets are private and cannot be seen by other people..
