### ISSUE TITLE
2.6.4: openvpn server picks the last key as it own aka Do not include cert nor key of allowed clients into servers config file

### ISSUE THREAD

**Issue by mmokrejs** [OpenVPN/openvpn#367]
In the server.conf file I included list of key and crt file of clients. Admittedly the key files were not necessary but the last-one was picked as server's it own key. I worked around it by providing this pair as the last one:

```
key keys/client1.key
cert keys/client1.crt
key keys/client2.key
cert keys/client2.crt

# lines below added as a workaround
key keys/myserver.key
cert keys/myserver.crt
```

I realized that in an error message sent to client1 which initiated the connection appeared a name of `client2`, which was weird:

```
Jul 16 15:37:32 client1 openvpn[50248]: VERIFY ERROR: depth=0, error=unsuitable certificate purpose: CN=client2, serial=144900055383528409947716382795632333551
Jul 16 15:37:32 client1 openvpn[50248]: OpenSSL: error:0A000086:SSL routines::certificate verify failed
Jul 16 15:37:32 client1 openvpn[50248]: TLS_ERROR: BIO read tls_read_plaintext error
Jul 16 15:37:32 client1 openvpn[50248]: TLS Error: TLS object -> incoming plaintext read error
Jul 16 15:37:32 client1 openvpn[50248]: TLS Error: TLS handshake failed
Jul 16 15:37:32 client1 openvpn[50248]: TCP/UDP: Closing socket
```

The `client2`'s key is listed on the line `priv_key_file = ` when a server starts up with `verb 5` set in its config file.

Does ordering of `key` or `crt` files  in a `server` config file eventually interfere with parsing `tls-crypt-v2` key file which is at the very top of my config file?

**Comment by cron2** [comment]
Just do not put more than one key or cert into the config - especially not a client cert into the server config.  This is not a valid setup, and funny things will happen.  There are special cases (in `<connection` blocks) where more than one key in a config can be valid, but this is exceptional, and a client key in a server config (or vice versa) still won't make sense.

In this case, OpenVPN sent the client2 cert back to client1, which then correctly stated "this is not a server cert, go away".

**Comment by mmokrejs** [comment]
@cron2 But why don't you install some roadblocks in processing the file? This is likely the reason people *disable* `remote-cert-tls server` options because it fails. Myself was puzzled by the message for 8 years and never realized until now on the server side I may not have more than one `key` and `cert` line (not even speaking certs can be concatenated, like people do to include in `ca.cert` their old RSA-SHA1 cert authority used to sign old clients and to merge in there a new cert authority.

Please install some measures on the server side config parsing code.

**Comment by cron2** [comment]
That's the downside of having a very flexible program - there are many many options, and we can't take any of them away (because they are there because someone out there found it important for them).

Some *combinations* of options really do not make sense, and we already have many 1000 lines of code trying to warn users about "do not use `x` and `y` at the same time" - which does not cover every possible variant, but it's plain impossible to cover each case.  At some point, you have to rely on users doing a bit of their own thinking, and reading the documentation.

**Comment by cron2** [comment]
That's the downside of having a very flexible program - there are many many options, and we can't take any of them away (because they are there because someone out there found it important for them).

Some *combinations* of options really do not make sense, and we already have many 1000 lines of code trying to warn users about "do not use `x` and `y` at the same time" - which does not cover every possible variant, but it's plain impossible to cover each case.  At some point, you have to rely on users doing a bit of their own thinking, and reading the documentation.

**Comment by schwabe** [comment]
This is something that OpenVPN has being forever. Only using the last value of a certain option. Fixing this or even giving a warning for this requires significant rewrite of the options parser. While we would love to do that, it is not very high on our priority list as this warning would be nice but currently does not justify rewriting the whole parser.

**Comment by mmokrejs** [comment]
I think I spent like 2 weeks in my life reading openvpn docs and searching for error messages and config files. I think it is a lot. Recently the whole weeked. I did an upgrade from 2.4 server and *still* do not have a working connection to any client (Linux, Android), maybe because I decided to go with `tls-crypt-v2`. Seems I will drop tls encryption like before to get going.

@schwabe But still you could parse twice the input config file and just count how many times `cert` or `key` is included. It is not ideal but common, there are more IO heavy tasks. Think how many people moved avay to e.g. Wireguard due to this or disabled tls altoghether.

**Comment by schwabe** [comment]
Parsing the config twice fail already fail with `--config stdin`. It is not as simple as you make it to be. If you think it is really simple, you are welcome to create a patch. And this behaviour of parsing is not limited to `cert` or `key`. It affects all options. 

For a `tls-crypt-v2`, you need 2.6.0 or higher on all clients.
