### ISSUE TITLE
openVPN 2.6.x : Issues with WINS, Netbios fails

### ISSUE THREAD

**Issue by ntulm** [OpenVPN/openvpn#373]
Hi,

I noticed problems with using the openVPN 2.6.x client on Windows PC (Windows 10).
Prior to this I used version 2.5.9 and everything worked fine.

But since version 2.6.x there are issues with resolving Netbios names and connecting to Samba share via Netbios name fails now.

The openVPN server pushes WINS Server IP to client via dhcp-options but it is no longer registered on Windows client when using version 2.6.x. ipconfig shows WINS-Server is defined with version 2.5.9 but none with version 2.6.x. 

Are there any config changes for Netbios support since 2.6? 
Or is this feature no longer supported?

**Comment by lstipakov** [comment]
Hi,

What has changed is that starting from 2.6 the default driver is now DCO, which doesn't do DHCP. I just checked the code and it looks like WINS works with DCO only when openvpn doesn't use interactive service. In this case we apply network settings by invoking `netsh.exe` directly by openvpn process, which runs under elevated privileges:

`NETSH: C:\WINDOWS\system32\netsh.exe interface ip set wins 27 static 10.8.0.1`

With interactive service (which is the default setup) we modify network settings by the privileged service, while openvpn process is running under limited privileges. Apparently we just lack the code which passes WINS settings from openvpn to the service process. This will be fixed in the next, 2.6.6, release.

Until that (I would say few weeks) if you need WINS you might want to disable DCO by adding `disable-dco` to the `.ovpn` profile.

Thanks for reporting this.

**Comment by ntulm** [comment]
Your workaround is working fine. Thanks a lot.
