### ISSUE TITLE
Issue installing Open vpn Client on RHEL9

### ISSUE THREAD

**Issue by mohamedharir** [OpenVPN/openvpn#383]
**Describe the bug**

after running:
# yum install yum-plugin-copr
# yum copr enable dsommers/openvpn3
# yum install openvpn3-client

we get:

Updating Subscription Management repositories.
Copr repo for openvpn3 owned by dsommers                                                                                                  14 kB/s |  13 kB     00:00    
Error: 
 Problem: conflicting requests
  - nothing provides libjsoncpp.so.25()(64bit) needed by openvpn3-client-20-2.el9.x86_64
  - nothing provides libprotobuf.so.25()(64bit) needed by openvpn3-client-20-2.el9.x86_64

**Version information (please complete the following information):**
 - OS: Red Hat Enterprise Linux 9.2 (Plow)     
     CPE OS Name: cpe:/o:redhat:enterprise_linux:9::baseos
          Kernel: Linux 5.14.0-284.18.1.el9_2.x86_64
    Architecture: x86-64
 Hardware Vendor: Lenovo

 - OpenVPN version: [3]

**Comment by flichtenheld** [comment]
Looking at https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux#FedoraRedHatEnterpriseLinuxCentOS the required information is there, but a bit hidden. Note the sentence

> If you are running Red Hat Enterprise Linux or its clones, you need to install both the Fedora EPEL repository and the yum copr module first. Instructions for enabling Fedora EPEL can be found here: [​https://fedoraproject.org/wiki/EPEL](https://fedoraproject.org/wiki/EPEL).

I just verified on a fresh RHEL9 system that the installation works fine if EPEL is enabled.

You might have missed that because it is not formatted as one of the "commands to execute" instructions. I will reformat the page a bit.
