### ISSUE TITLE
User writable config folder

### ISSUE THREAD

**Issue by EntityinArray** [OpenVPN/openvpn#387]
OpenVPN reads config files from `C:/OpenVPN/config` by default on Windows, which is not user writable.
Why not also read a user-specific folder, for example `C:/Users/user/AppData/Roaming/OpenVPN/config`?

**Comment by selvanair** [comment]
There is no hard-coded default location for reading configs from. If you execute openvpn.exe from command line, it reads the config file from the current directory for relative paths, and the specified absolute path otherwise.

You are probably referring to OpenVPN-GUI. If so, it looks for configs in three locations, one of which is in user's profile: `C:\Program Files\OpenVPN\config`, `C:\Program Files\OpenVPN\config-auto` and `%USERPROFILE%\OpenVPN\config`. So, use the latter for "user-writable" location. 

In case you are referring to openvpn automatic service which starts tunnels at boot, it reads from the second location of the above three. For that service running as SYSTEM, reading from a user's profile is not appropriate.
