### ISSUE TITLE
The dns option breaks third-party tools that read the DNS configuration

### ISSUE THREAD

**Issue by dud225** [OpenVPN/openvpn#421]
The newly added  `dns` option is meant to replace `dhcp-option` soon. With this change, the openvpn client, depending on its version, doesn't interpret the DNS configurations sent by the server in the same way.

On my case the server has a configuration similar to:
```
push "dhcp-option DOMAIN mydomain"
```

On OpenVPN 2.5.5 I get:
```
dhcp-option DOMAIN mydomain
```

whereas on OpenVPN 2.6.3 I get:
```
dns server 10 resolve-domains mydomain
```

However there are several third-party tools like https://github.com/jonathanio/update-systemd-resolved and https://github.com/NetworkManager/NetworkManager-openvpn that break because they rely on the earlier behaviour.

The option `--compat-mode` doesn't help here.

I would suggest to keep the backward compatibility by emitting the previous `foreign_option_X=dhcp-option` env vars in addition to the new ones `dns_server_X_resolve_domain_X`.

**Comment by d12fk** [comment]
`resolve-domains` are not added to the environment as foreign_option_X because the semantics are different to what could be set by pushing DOMAIN, SEARCH-DOMAIN and ADAPTER_DOMAIN_SUFFIX via `dhcp-option`. All three values represent domain suffixes that are added to not fully qualified hostnames. `resolve-domains` are domain names that are used for split DNS, which is treated as a different set of domains with the new option,  the 'search-domains' domains option is what you want to push on the server side to emulate the previous behavior.
