### ISSUE TITLE
OpenVPN server 2.4.0 - 2.4.4 and dco-enabled client incompatibility

### ISSUE THREAD

**Issue by SkyArbor** [OpenVPN/openvpn#422]
I don't know if it belongs to here, but since I can reproduce the issue on OpenVPN GUI 2.6.6 and 2.6.0 but not 2.5.9, I thought it has something to do with the new driver.
My OpenVPN server is behind NAT, and has a topology roughly like this:
 
`
192.168.0.3 (client) <---> 103.116.76.243 (NAT border) <---> 10.111.213.190 (server)
`

The `.pcap` files indicates that client and server communication should be okay (and it works on OpenVPN GUI 2.5.9). Also I found the `tun0` device on server has data flowed in and out. However, I can't find any data received on client `dco` device, through there are VPN packets in the ethernet capture file.
 
Here are the packets and log files on both sides (Hopefully no sensitive data). The client uses port 35663, udp protocol.
[ovpn_issue.zip](https://github.com/OpenVPN/ovpn-dco-win/files/12831944/ovpn_issue.zip)

**Comment by SkyArbor** [comment]
> Could you provide openvpn client log with `verb 4` with and without `disable-dco` ?


[disable_dco.log](https://github.com/OpenVPN/openvpn/files/12836037/disable_dco.log)

**Comment by lstipakov** [comment]
Thanks for reporting this. The problem is that server sends packets in `DATA_V1` format which DCO driver doesn't understand. This happens with the servers 2.4.0 - 2.4.4. Starting from 2.4.5 the server sends packets in `DATA_V2 `and problem should go away. With older servers you need to enable non-AEAD ciphers on the client side which disables DCO, so the problem doesn't exist there.

This is indeed an overlook from our side. On the client (driver) side we might want to detect `DATA_V1 `packets and notify userspace, which will log it ("data format is incompatible with dco, upgrade your server or use `--disable-dco`") and abort connection.

**Comment by piotr-dobrogost** [comment]
When using OpenVPN 2.7.3 with kernel 7.0.8-200.fc44.x86_64 (Fedora 44) and server OpenVPN 2.4.0, the tunnel is established, but no traffic comes through. I raised this issue at https://sourceforge.net/p/openvpn/mailman/openvpn-devel/thread/d7bd1d3d-c9e3-4f4a-ba75-0fdccb5006f5%40unstable.cc/#msg59334334, but the source of the problem hasn't been found after analyzing client-side logs. I suspect it's the same issue as raised here.

> This is indeed an overlook from our side. On the client (driver) side we might want to detect DATA_V1 packets and notify userspace, which will log it ("data format is incompatible with dco, upgrade your server or use --disable-dco") and abort connection.

It looks like this hasn't been done, as there's neither a message in the logs nor the connection is aborted.

**Comment by schwabe** [comment]
@piotr-dobrogost do not hiject a different issue for the problem that is not helpf and just makes the github issues/discussion messy. One issue should be kept to one topic.

**Comment by piotr-dobrogost** [comment]
I think this is the same issue. The behavior we observe shows that the anti-measures I cited were not introduced or do not work.

**Comment by schwabe** [comment]
This issue discussed here only happens with these very specific openvpn version on the server side. Is your server running 2.4.0 to 2.4.4?

**Comment by piotr-dobrogost** [comment]
Yes, the server is 2.4.0 and this information is present in my comment above.
I raised my issue on the list, and we've been trying to establish the cause, but without success. Today, someone else pointed me to this issue.
The thread is here https://sourceforge.net/p/openvpn/mailman/openvpn-devel/thread/d7bd1d3d-c9e3-4f4a-ba75-0fdccb5006f5%40unstable.cc/#msg59334334
Also, I raised the problem here https://discussion.fedoraproject.org/t/openvpn-tunnel-stopped-working-after-upgrade-to-fedora-44/191218

**Comment by cron2** [comment]
> Yes, the server is 2.4.0

please upgrade.  2.4.0 is close to 10 years old, and the list of bugs fixed since then, some of them security relevant, is very long.

That said, I think we might need to revisit the code that detects the problem and warns about it

```
            /*
             * If DCO is enabled, the kernel drivers require that the
             * other end only sends P_DATA_V2 packets. V1 are unknown
             * to kernel and passed to userland, but we cannot handle them
             * either because crypto context is missing - so drop the packet.
             *
             * This can only happen with particular old (2.4.0-2.4.4) servers.
             */
            if ((opcode == P_DATA_V1) && dco_enabled(&c->options))
            {
                msg(D_LINK_ERRORS, "Data Channel Offload doesn't support DATA_V1 packets. "
                                   "Upgrade your server to 2.4.5 or newer.");
                c->c2.buf.len = 0;
            }
```

... because 2.7 with the in-kernel DCO does no longer pass "unknown" data packets to userland - so we do not see these packets anymore and can not warn about it.   @ordex, any good idea?

**Comment by ordex** [comment]
> [@ordex](https://github.com/ordex), any good idea?

can we complain when we don't see any peer-id in the PUSH_REPLY?

**Comment by schwabe** [comment]
@ordex is P_DATA_V1 special cased in the kernel that we do not forward it to userspace? Or do we not forward any unknown op codes to userspace? The latter would be bad since then cannot easily extend the protocol anymore.

**Comment by cron2** [comment]
Other direction... 2.4.0 started supporting DATA_V2 client->server (and pushed peer-id), but did not send V2 packets server->client ("because why should we, there is only 1 server").  This was added to 2.4.5...

commit 6232c7b3827f90d9b25135c523703204bc2095c0
Author: Steffan Karger <steffan@karger.me>
Date:   Fri Nov 24 14:58:23 2017 +0100

    Use P_DATA_V2 for server->client packets too
    
    P_DATA_V2 introduced the peer-id.  This allows clients to float, but as a
    side-effect 32-bit aligns the encrypted data.  That alignment improves
    performance particularly on cheaper/older CPUs.  So although servers don't
    actually have a peer-id, still use the V2 packet format (with a zero-id)
    for server->client traffic too.

... which has the side effect of helping with DCO - which we didn't notice until 5 years later...

So all we know is "we use V2 for sending, and there is an incoming V1 packet".  Back in the day, "unrecognized" data packets were sent to userspace for processing, but that whole code path ("send data packets to userspace") was abandoned, iirc.

**Comment by cron2** [comment]
(I might misremember, but then @piotr-dobrogost really should have seen the warning message from the code fragment quoted above...)

**Comment by ordex** [comment]
> [@ordex](https://github.com/ordex) is P_DATA_V1 special cased in the kernel

yes.
During the upstream debate it was concluded that DATA packets are not sent to userspace, while all other opcodes are.
I think this came from the fact that TCP was already doing something like this, for some reason, and so we made UDP behave the same.

So DATA_V* stays in kernel. It's just that DATA_V1 is dropped.

**Comment by ordex** [comment]
> 2.4.0 started supporting DATA_V2 client->server (and pushed peer-id)

so the server understands DATA_V2, behaves as if it did DATA_V2, but then sends V1. darn.
This is why in the packet dump we could see packets going both directions matching the ping timing...

**Comment by cron2** [comment]
Technically it does not "behaves as if it did DATA_V2" (because it was well-understood back then that it would send V1 and receive V2).  But for all practical means, yes, normally receiving a peer-id is a good signal for "V2 in both directions".
