### ISSUE TITLE
Q: how to route everything through the VPN *except* for localhost

### ISSUE THREAD

**Issue by costa** [OpenVPN/openvpn#428]
I'm using `redirect-gateway def1` but this includes localhost (127.0.0.1).
I figure this is some sort of a `route ...` config command, but what are the required arguments?

**Comment by cron2** [comment]
with routing, it's always "more specific wins".  So having a localhost route which is more specific than a default route (/0 or 2 times /1) automatically excldues localhost from the VPN.

**Comment by costa** [comment]
@cron2 Thank you, this is exactly the kind of responses to this kind of inquiries I've seen on the internet prior to posting this question.

It helps not.

For the sake of those who stumble upon similar issues, here's my response:

If one invests, maybe 30 seconds more, maybe a whole minute more in helping a fellow dev, one may realise that:
1) one line of config would be worth more than this kind of education (which is abundant all over the interwebs already)
2) that line of config may be a bit trickier than it seems (which gateway would you route 127.0.0.1 through, huh?)
and finally
3) the issue is actually something else entirely, `redirect-gateway ...` does not in fact result in routing localhost anywhere.

My actual issue was with something else: I tunnel my OpenVPN server to a localhost port, and I forgot to include that specific exceptional route for the tunnel. The appropriate client config line in question would be:
`route <TUNNELED HOST IP> 255.255.255.255 net_gateway`

**Comment by cron2** [comment]
> @cron2 Thank you, this is exactly the kind of responses to this kind of inquiries I've seen on the internet prior to posting this question.

Maybe that is "because it's the correct answer for the problem you stated"?

We as OpenVPN developers usually understand quite well how and why packets flow, so without extra information on why you think such a route might be needed, this is the *only* correct answer...

> 3. the issue is actually something else entirely, `redirect-gateway ...` does not in fact result in routing localhost anywhere.
> 
> My actual issue was with something else: I tunnel my OpenVPN server to a localhost port, and I forgot to include that specific exceptional route for the tunnel. The appropriate client config line in question would be: `route <TUNNELED HOST IP> 255.255.255.255 net_gateway`

This makes the scenario more clear, thank you.

Indeed, if OpenVPN is not directly talking to the remote VPN server but "to localhost" it would not know a host route has to be set up, to circumvent the redirected default gateway - and without that host route, the software that does the tunneling won't be able to reach its tunnel end.
