### ISSUE TITLE
"cd" option fails in OpenVPN version 2.6.7

### ISSUE THREAD

**Issue by trispace** [OpenVPN/openvpn#448]
**Describe the bug**
After updating to OpenVPN 2.6.7 [git:v2.6.7/53c9033317b3b8fd] from OpenVPN 2.6.6 the "cd" option in the configuration file prevents OpenVPN from connecting due to the following error:

```
2023-11-10 16:28:13 cd to 'c:\Program Files\OpenVPN\config\test' failed: No such file or directory (errno=2)
2023-11-10 16:28:13 Exiting due to fatal error
```

in the configuration file "cd" was used like this:
```
[...]
cd "c:\\Program Files\\OpenVPN\\config\\test"
ca ca.crt
tls-auth ta.key 1
[...]
```

the mentioned directory exists and also the ACEs were not changed

```
PS C:\> Get-Item "c:\Program Files\OpenVPN\config\test"

    Directory: C:\Program Files\OpenVPN\config

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          06.06.2021    14:59                test
```

A trace of the I/O operations of the openvpn.exe process shows that the configuration file is opened and read, but no access to the "test" directory or attempt to read files from it are visible in the trace.

Also replacing the "\\" with "//" does not resolve the issue.

**To Reproduce**
Create a OpenVPN configuration file with the "cd" option and try to connect.

**Expected behavior**
OpenVPN connects as it did in previous version 2.6.6

**Version information (please complete the following information):**
 - OS: Windows 22H2 Build 19045.3570
 - OpenVPN version: 2.6.7

**Comment by cron2** [comment]
Thanks for the report.  From 2.6.6 to 2.6.7, windows building was changed from "MSVC with MSVC build files" to "CMake" (as we do in master since quite a while).  The CMakefile had an omission regarding chdir() on windows, so the compile resulted in "there is no chdir() function on Windows" and thus all `--cd` configs failed.  We are sorry about this.

A new windows installer will be released "really soon".  A build system patch is already in review.

**Comment by trispace** [comment]
Many thanks for the extremely fast response and fix!
