### ISSUE TITLE
is there a way to use tcp mode like udp mode with multihome in the case of openvpn work with keepalived vip

### ISSUE THREAD

**Issue by bobz965** [OpenVPN/openvpn#478]
**IMPORTANT NOTE**
Bugs about OpenVPN Access Server, OpenVPN Connect or any other product by OpenVPN Inc. should be directly reported to OpenVPN Inc. at https://support.openvpn.net

**Describe the bug**

OpenVPN UDP can work with keepalive VIP by configuring `multihome`,
but `multihome` only works in UDP. 

Is there a way to use OpenVPN TCP with keepalive VIP like the config option `multihome` in UDP ???

**To Reproduce**
Steps to reproduce the behavior. Please make sure to not post any secrets like keys and passwords.

**Expected behavior**

**Version information (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - OpenVPN version: [e.g. 2.5.8]
 - Repeat for peer if relevant

**Additional context**

**Comment by cron2** [comment]
TCP mode does not need the `multihome` option, because with TCP the kernel will take care of the extra houskeeping needed.

That said, we have removed the check in 2.6.x - so using `multihome` on a TCP server will no longer cause an option error, but will be silently ignoried (there is nothing to do for OpenVPN in the TCP case).

**Comment by bobz965** [comment]
thanks
