### ISSUE TITLE
Split public ip

### ISSUE THREAD

**Issue by MrSipping** [OpenVPN/openvpn#579]
Hello everyone, I have this problem and I don't know if it can be solved, I'm using gitlab to deploy on my servers but I have this problem where some servers are only reachable by vpn and others are not. I wanted to know if there was a possibility of configuration where activating vpn doesn't affect my public ip or in any case uses vpn for these servers but for the servers not under vpn uses its public ip not modified.

Thank you all

**Comment by ordex** [comment]
Yes, it's called split-tunnel. it simply consists in configuring routing according to your needs so that only some IP/networks are routed through the VPN.
Note that this is not an OpenVPN specific problem, but a generic networking one.

Should you need further asisstance, please check our forum or mailing list.

This is a bug tracker used to report bug only.
