### ISSUE TITLE
OPTIONS ERROR: Failed to negotiate with cypher

### ISSUE THREAD

**Issue by mcrite** [OpenVPN/openvpn#592]
I get this same error over and over again when trying to connect with multiple profiles.  Any assistance would be great.

2020-11-13 16:05:38 OPTIONS ERROR: failed to negotiate cipher with server. Configure --data-ciphers-fallback if you want to connect to this server.
2020-11-13 16:05:38 ERROR: Failed to apply push options
2020-11-13 16:05:38 Failed to open tun/tap interface
2020-11-13 16:05:38 SIGUSR1[soft,process-push-msg-failed] received, process restarting
2020-11-13 16:05:38 Restart pause, 5 second(s)

**Comment by francescor** [comment]
solved it, too, by only replacing  

```diff
-cipher AES-256-CBC
+data-ciphers AES-256-CBC
```

(it works if I add it, too)

Now I can connect with CLI, but when I import that working vpn configuration file in Gnome NetworkManager I see this `data-ciphers` is totally ignored, so the vpn still does not work with  NetworkManager.

I am curious to understand the logic that is causing this pretty serious issue with working openvpn configurations (pls try to understand, I have to explain not just to my boss, but to customers and our users)

What is the version of Openvpn affected by this issue? (I have OpenVPN 2.6.12 in Fedora 40, updated)

**Comment by francescor** [comment]
I read this in https://openvpn.net/community-resources/reference-manual-for-openvpn-2-5/  (so for version 2.5.*)

```
cipher: 

This option is deprecated for server-client mode. --data-ciphers or possibly --data-ciphers-fallback` should be used instead.
```
what version of 2.6 started to need `data-ciphers` ?

**Comment by cron2** [comment]
> I am curious to understand the logic that is causing this pretty serious issue with working openvpn configurations (pls try to understand, I have to explain not just to my boss, but to customers and our users)

The real problem here is that you are connecting to a server that is not behaving correctly, or not configured correctly.  The expectation is that the client signals to the server "I can handle cipher AES-128-GCM, AES-256-GCM, chacha-poly" and the server will then pick and use one of this list.

A server that insists on only supporting AES-256-CBC, not supporting any of the GCM ciphers, and failing to follow cipher negotiation protocols is not behaving correctly - so to make this work, it needs the changes in the client config that you are observing.  This is all documented in the 2.6.0 release notes.

> What is the version of Openvpn affected by this issue? (I have OpenVPN 2.6.12 in Fedora 40, updated)

2.6.0 deprecated ``--cipher``.  cipher negotiation was introduced in 2.4.0 (!).

See also https://community.openvpn.net/openvpn/wiki/CipherNegotiation for a (short) overview of the interactions of server versions 

So, what server version are you using?

**Comment by francescor** [comment]
I've updated to Softether v. 4.42  (latest) but the issue is still there.  I guess I have to replace the Centos 7 server?

**Comment by cron2** [comment]
> I've updated to Softether v. 4.42 (latest) but the issue is still there. I guess I have to replace the Centos 7 server?

You will need to open a ticket with Softether how to make the server more well-behaved.  It's a 3rd party implementation, and we have no control on what they do (but we do regularily get bug reports because of incompatibilities).
