### ISSUE TITLE
client-disconnect trigger delay？

### ISSUE THREAD

**Issue by balck-paint** [OpenVPN/openvpn#593]
I am currently using openvpn version 2.5.10, and I have observed a significant delay in the trigger time of the client-disconnect script, which is not immediately triggered, and currently has a delay of about 4 minutes. I would like to ask how to set up this script to trigger more timely?
I know this is probably not a bug, but a feature. Maybe it's to take care of some aspects, but for me it's more about timeliness. So if there is a configuration to set this up, please let me know, thanks

**Comment by balck-paint** [comment]
I seem to have found that this is affected by --keepalive, if the configuration of this parameter is relatively small, is there any negative impact?

**Comment by cron2** [comment]
On a UDP connection, the OpenVPN server can not really distinguish between a client not sending anything "because there is nothing to send" and a client that "got disconnected", so `--keepalive` is the reliable way to determine "nothing there anymore".

For normal client disconnects ("user pressing disconnect button") adding `--explicit-exit-notify` will make the client send a "goodbye!" message to the server, so the server knows right away.  But this will not help for all cases, like "the client's DSL line broke" etc.

`--keepalive` has a certain impact on CPU usage and bandwidth, so it depends on your environment - if you have a handful of clients, sending a packet to every client every 2s is not too bad.  If you have 1000 concurrent users, this would add quite a bit of CPU and bandwidth...

**Comment by balck-paint** [comment]
> On a UDP connection, the OpenVPN server can not really distinguish between a client not sending anything "because there is nothing to send" and a client that "got disconnected", so `--keepalive` is the reliable way to determine "nothing there anymore".在UDP连接上，OpenVPN服务器无法真正区分“因为没有什么可发送”的客户端没有发送任何东西“和”断开连接“的客户端，因此`--keepalive`是确定”不再有任何内容“的可靠方法。
> 
> For normal client disconnects ("user pressing disconnect button") adding `--explicit-exit-notify` will make the client send a "goodbye!" message to the server, so the server knows right away. But this will not help for all cases, like "the client's DSL line broke" etc.
> 
> `--keepalive` has a certain impact on CPU usage and bandwidth, so it depends on your environment - if you have a handful of clients, sending a packet to every client every 2s is not too bad. If you have 1000 concurrent users, this would add quite a bit of CPU and bandwidth...对 CPU 使用率和带宽有一定的影响，所以这取决于你的环境 - 如果你有几个客户端，每 2 秒向每个客户端发送一个数据包还不错。如果您有 1000 个并发用户，这将增加相当多的 CPU 和带宽......

Thanks, this configuration works. Client exit is to exit normally, kill the process or other unexpected circumstances will not send this command? How does linux make a client exit normally?

**Comment by cron2** [comment]
"normal kill" (ctrl-c or kill -HUP) will also send the explicit-exit-notify.  "kill -9" or "unplug the power cable" won't, obviously :-)
